In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()
pd.set_option('display.max_columns', None)

/Users/hardiksharma/anaconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


## Step 1 : Create a multi-class dataset

In [2]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000,n_features=10,n_classes=3, n_informative=3)

In [3]:
X.shape, y.shape

((1000, 10), (1000,))

## Step 2 : Divide into Training and Testing

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30)

## Step 3 : Model Training

In [5]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(multi_class='ovr')
logistic.fit(X_train, y_train)
y_pred = logistic.predict(X_test)

/Users/hardiksharma/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


## Step 4 : Performance Metrics

In [6]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [7]:
score = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(score)
print(cm)
print(classification_report(y_test, y_pred))

0.4266666666666667
[[46 24 27]
 [33 28 33]
 [31 24 54]]
              precision    recall  f1-score   support

           0       0.42      0.47      0.44        97
           1       0.37      0.30      0.33        94
           2       0.47      0.50      0.48       109

    accuracy                           0.43       300
   macro avg       0.42      0.42      0.42       300
weighted avg       0.42      0.43      0.42       300



## Step 5 : Try Hyperparameter Tuning and Cross Validation yourself